#pragma once

enum game_option_types {
    OPT_PAGE_INPUT,
    OPT_PAGE_MAPSCREEN,
    OPT_PAGE_TEXT,
    OPT_PAGE_GAMEPLAY,
    OPT_PAGE_DISTURBANCE,
    OPT_PAGE_BIRTH,
    OPT_PAGE_AUTODESTROY,
    OPT_PAGE_PLAYRECORD,
    OPT_PAGE_HIDE,
};
