#pragma once

enum parse_error_type : int {
    PARSE_ERROR_NONE = 0,
    PARSE_ERROR_GENERIC = 1,
    PARSE_ERROR_OBSOLETE_FILE = 2,
    PARSE_ERROR_MISSING_RECORD_HEADER = 3,
    PARSE_ERROR_NON_SEQUENTIAL_RECORDS = 4,
    PARSE_ERROR_INVALID_FLAG = 5,
    PARSE_ERROR_UNDEFINED_DIRECTIVE = 6,
    PARSE_ERROR_OUT_OF_MEMORY = 7,
    PARSE_ERROR_OUT_OF_BOUNDS = 8,
    PARSE_ERROR_TOO_FEW_ARGUMENTS = 9,
    PARSE_ERROR_UNDEFINED_TERRAIN_TAG = 10,
    PAESE_ERROR_INVALID_PVAL = 11,
    PARSE_ERROR_MAX,
};
