#pragma once

enum player_personality_type {
    PERSONALITY_ORDINARY = 0,
    PERSONALITY_MIGHTY = 1,
    PERSONALITY_SHREWD = 2,
    PERSONALITY_PIOUS = 3,
    PERSONALITY_NIMBLE = 4,
    PERSONALITY_FEARLESS = 5,
    PERSONALITY_COMBAT = 6,
    PERSONALITY_LAZY = 7,
    PERSONALITY_SEXY = 8,
    PERSONALITY_LUCKY = 9,
    PERSONALITY_PATIENT = 10,
    PERSONALITY_MUNCHKIN = 11,
    PERSONALITY_CHARGEMAN = 12,
    MAX_PERSONALITIES = 13,
};
