#pragma once

enum class MonsterDropType {
    ONLY_GOLD = 0,
    ONLY_ITEM = 1,
    DROP_GOOD = 2,
    DROP_GREAT = 3,
    DROP_CORPSE = 4,
    DROP_SKELETON = 5,
    DROP_60 = 6,
    DROP_90 = 7,
    DROP_1D2 = 8,
    DROP_2D2 = 9,
    DROP_3D2 = 10,
    DROP_4D2 = 11,
    DROP_COPPER = 12,
    DROP_SILVER = 13,
    DROP_GARNET = 14,
    DROP_GOLD = 15,
    DROP_OPAL = 16,
    DROP_SAPPHIRE = 17,
    DROP_RUBY = 18,
    DROP_DIAMOND = 19,
    DROP_EMERALD = 20,
    DROP_MITHRIL = 21,
    DROP_ADAMANTITE = 22,
    MAX,
};
