#pragma once

/* The "sval" codes for TV_FOOD */
enum sv_food_type {
    SV_FOOD_POISON = 0,
    SV_FOOD_BLINDNESS = 1,
    SV_FOOD_PARANOIA = 2,
    SV_FOOD_CONFUSION = 3,
    SV_FOOD_HALLUCINATION = 4,
    SV_FOOD_PARALYSIS = 5,
    SV_FOOD_WEAKNESS = 6,
    SV_FOOD_SICKNESS = 7,
    SV_FOOD_STUPIDITY = 8,
    SV_FOOD_NAIVETY = 9,
    SV_FOOD_UNHEALTH = 10,
    SV_FOOD_DISEASE = 11,
    SV_FOOD_CURE_POISON = 12,
    SV_FOOD_CURE_BLINDNESS = 13,
    SV_FOOD_CURE_PARANOIA = 14,
    SV_FOOD_CURE_CONFUSION = 15,
    SV_FOOD_CURE_SERIOUS = 16,
    SV_FOOD_RESTORE_STR = 17,
    SV_FOOD_RESTORE_CON = 18,
    SV_FOOD_RESTORING = 19,
    /* many missing mushrooms */
    SV_FOOD_BISCUIT = 32,
    SV_FOOD_JERKY = 33,
    SV_FOOD_RATION = 35,
    SV_FOOD_SLIME_MOLD = 36,
    SV_FOOD_WAYBREAD = 37,
    SV_FOOD_PINT_OF_ALE = 38,
    SV_FOOD_PINT_OF_WINE = 39,
};
