#!/bin/sh

jp=`grep "#define JP" autoconf.h | wc -l`

if test $jp -eq 1; then
    eval src_file=\${$#}

    trap '' INT
    backup=`mktemp`
    mv $src_file $backup
    nkf -e $backup > $src_file
    $@
    mv $backup $src_file
else
    $@
fi
