name: Build and test with MSVC
on:
  workflow_call:

  # 手動トリガーを許可
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v4

      - name: Restore Nuget Packages
        run: |
          NuGet restore .\VisualStudio\Hengband.sln

      - name: Run build test
        run: |
          MSBuild -warnAsError .\VisualStudio\Hengband.sln /t:Rebuild /p:Configuration=Debug

      # 上のビルドで HengbandTest プロジェクトも生成される。
      # doctest はテストが失敗すると非ゼロの終了コードを返す
      - name: Run unit tests
        run: |
          .\VisualStudio\Hengband\Debug\hengband-test.exe
